version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unused
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 160
      statements: 100
    gocyclo:
      min-complexity: 36
    lll:
      line-length: 140
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
