version: 2.1

references:
  nix_image: &nix_image
    - image: cimg/base:current
      user: root
      environment:
        LOCALE_ARCHIVE: /usr/lib/locale/locale-archive

  default: &default
    working_directory: ~/go-core

  nix_shell: &nix_shell
    shell: /nix/var/nix/profiles/default/bin/nix develop .# -c bash -euo pipefail

  commands:
    setup_nix: &setup_nix
      name: Set up nix
      command: |
        curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix \
        | sh -s -- install linux --init none --no-confirm \
          --extra-conf "cores = 0"
        echo '. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' >> $BASH_ENV

jobs:
  go_build:
    <<: *default
    docker: *nix_image
    steps:
      - checkout
      - run: *setup_nix

      - restore_cache:
          keys:
          - v1-go-dependencies-{{ checksum "go.sum" }}

      - run:
          name: linter
          <<: *nix_shell
          command: |
            make linter

      - run:
          name: test
          <<: *nix_shell
          command: |
            make test

      - save_cache:
          key: v1-go-dependencies-{{ checksum "go.sum" }}
          paths:
            - ~/go/pkg

workflows:
  builds_deploy:
    jobs:
      - go_build
