version: 2.1

references:
  go_image: &go_image
    - image: cimg/go:1.18

  default: &default
    working_directory: ~/go-core

  commands:
    install_dependencies: &install_dependencies
      name: Install Dependencies
      command: |
        sudo apt-get update && \
        sudo apt-get upgrade -y && \
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends \
            autoconf \
            automake \
            ca-certificates \
            curl \
            gifsicle \
            htop \
            libtool \
            libvips-dev \
            make \
            nasm \
            net-tools \
            openssl \
            pkg-config \
            pngquant \
            telnet \
            unzip \
            vim \
            wget \
        && \
          sudo update-ca-certificates \
        && \
          cd /tmp && \
          wget https://github.com/mozilla/mozjpeg/archive/v3.3.1.tar.gz && \
          tar -zxvf v3.3.1.tar.gz && \
          cd mozjpeg-3.3.1 && \
          autoreconf -fiv && \
          mkdir build && cd build && \
          sh ../configure && \
          sudo make install && \
          sudo ln -s /opt/mozjpeg/bin/* /usr/local/bin/

    setup_environment_variable: &setup_environment_variable
      name: Environment settings
      command: |
        # XXX: Watch out single quote and double quote due to `before eval`, `after eval`
        #      We recommend to usually use single quote is better.
        #
        echo 'export PATH=/go/bin:/usr/local/go/bin:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:$PATH' >> $BASH_ENV
        echo 'alias ll="ls -alt"' >> $BASH_ENV
        echo 'alias ..="cd ../"' >> $BASH_ENV
        echo 'alias ...="cd ../../"' >> $BASH_ENV

        echo 'export GOOS=linux' >> $BASH_ENV
        echo 'export GOARCH=amd64' >> $BASH_ENV
        echo 'export GO111MODULE=on' >> $BASH_ENV

        if [ $CIRCLE_BRANCH == "master" ]; then
          echo 'export AWS_DEFAULT_REGION=ap-northeast-1'                                   >> $BASH_ENV
          echo 'export AWS_REGION=ap-northeast-1'                                           >> $BASH_ENV
        else
          echo 'export AWS_DEFAULT_REGION=ap-northeast-2'                                   >> $BASH_ENV
          echo 'export AWS_REGION=ap-northeast-2'                                           >> $BASH_ENV
        fi

jobs:
  # Golang CircleCI 2.0 configuration file
  #
  # Check https://circleci.com/docs/2.0/language-go/ for more details
  go_build:
    <<: *default
    working_directory: ~/go/src/github.com/eiicon-company/go-core
    docker: *go_image
    steps:
      - checkout

      - run: *install_dependencies
      - run: *setup_environment_variable

      - restore_cache:
          keys:
          - v1-go-dependencies-{{ checksum "go.sum" }}

      - run:
          name: misspell
          command: |
            make misspell

      - run:
          name: linter
          command: |
            make linter

      - run:
          name: golint
          command: |
            make golint

      - run:
          name: test
          command: |
            make test || make test || make test

      - save_cache:
          key: v1-go-dependencies-{{ checksum "go.sum" }}
          paths:
            - ~/go/pkg

workflows:
  version: 2.1
  builds_deploy:
    jobs:
      - go_build
