// Code generated by MockGen. DO NOT EDIT.
// Source: overflow.go
//
// Generated by this command:
//
//	mockgen -source=overflow.go -package=mock_scast -destination=./mock/overflow.go
//

// Package mock_scast is a generated GoMock package.
package mock_scast
