name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize

  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31
      with:
        install_options: --no-daemon
        extra_nix_config: |
          substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://cache.iog.io
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
          keep-env-derivations = true
          keep-outputs = true
          extra-experimental-features = ca-derivations
          cores = 0

    - uses: nix-community/cache-nix-action@v6
      with:
        primary-key: v1-nix-cache-${{ runner.os }}-${{ github.event.repository.name }}-${{ hashFiles('flake.lock') }}
        restore-prefixes-first-match: v1-nix-cache-${{ runner.os }}-${{ github.event.repository.name }}-

    - uses: nicknovitski/nix-develop@v1
      with:
        arguments: .#

    - name: Lint
      run: |
        make linter
        git ls-files '*.nix' | xargs nixfmt -c
        actionlint

    - name: Test
      run: |
        make test

