name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize

  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            cores = 0
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: nicknovitski/nix-develop@v1

      - uses: hoverkraft-tech/compose-action@v2
        with:
          compose-file: compose.yml

      - name: Lint
        run: |
          make linter
          git ls-files '*.nix' | xargs nixfmt -c
          actionlint

      - name: Test
        run: |
          make test
